### ISSUE TITLE
Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found on timbru31/node-chrome:alpine

### ISSUE THREAD

**Issue by oliverlj** [timbru31/docker-node-chrome#342]
Please find a ci log with the error here :
https://gitlab.com/fritzy/front/fz-front-simulator/-/jobs/1606202130

**Comment by oliverlj** [comment]
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1279900-harfbuzz-3-0-released-with-unicode-14-0-support-more-apis-considered-stable/page2

Here the same error related to HarfBuzz

**Comment by timbru31** [comment]
Thanks, I'll check this.

**Comment by oliverlj** [comment]
https://github.com/harfbuzz/harfbuzz/issues/3216

"Same issue here. Any fix for this on alpine?

That is not a Harfbuzz issue. You need to take that up with the Alpine packagers. If I had to guess I'd say they probably stripped the vendored version of HB in the Chromium build and linked it to their system package instead, then swapped it an incompatible version. Chromium was deliberately using unstable interfaces, but they also bundle the version they required. The Alpine packagers need to sort that out."

**Comment by timbru31** [comment]
I fear that this is nothing I can fix, and rather the Alpine guys need to take care of 😞

**Comment by timbru31** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/13026 - Alpine already fixed the bug

**Comment by oliverlj** [comment]
good :)

**Comment by oliverlj** [comment]
just tested new image deployed => successfull !
