### ISSUE TITLE
Node gallium images fail to invoke npm when using run scripts

### ISSUE THREAD

**Issue by iouym** [timbru31/docker-node-chrome#364]
It looks like the docker images that use `node:gallium` (`node:16`) fail to execute run scripts (e.g. `npm run test`) which seems to be related to issue https://github.com/nodejs/docker-node/issues/1734

Not too sure what the best path forward is, it looks like this was introduced as of node image v16.15.1. The immediate workaround is to use the node:16.15.0 image, figured I'd flag it here as an FYI 🙂

Perhaps a consideration is having support for version specific images (e.g. `docker pull timbru31/node-chrome:16.15.0`)

**Comment by timbru31** [comment]
Thanks for the update - was not aware of such an issue.

> Perhaps a consideration is having support for version specific images (e.g. docker pull timbru31/node-chrome:16.15.0)

Yes, this might be a good addition, but requires manual work for each new Node.js release.

**Comment by timbru31** [comment]
I've ran the example in the linked issue with both:
```sh
docker run --rm -v $PWD:/app --workdir /app --entrypoint npm timbru31/node-chrome:16-alpine run ver
docker run --rm -v $PWD:/app --workdir /app --entrypoint npm timbru31/node-chrome:16 run ver
```

Both work fine for me. Closing. Let me know if any new issues arise.
