### ISSUE TITLE
arm64 builds only for alpine

### ISSUE THREAD

**Issue by thomasmattheussen** [timbru31/docker-node-chrome#380]
Hi,

Is there any reason why the arm64 architecture is only available for the alpine image? I see that the node base images are all available for arm64 as well.

My situation: I need to install some extra dependencies ([Swift](https://www.swift.org/getting-started/)) that are not available in alpine. But I want to build this on my mac M1 as well as in a CI pipeline. Right now I'm "stuck" by having to build for amd64 which is incredibly slow on my mac M1 due to emulation.

(I'm way out of my comfort zone in all this, so excuse me if this a weird question 😅 )

**Comment by timbru31** [comment]
In the past there were probably restrictions by having the base images or the Chrome dependency not available for arm64.
I'll explore if this has changed.

**Comment by timbru31** [comment]
Chrome is still only available for amd64. I'll consider switching to Chromium instead as I doubt one would need things as Google account syncing in a Docker image.

**Comment by thomasmattheussen** [comment]
That'd be nice!
