### ISSUE TITLE
CI is broken (for consumers), because images not use Chromium instead of Chrome

### ISSUE THREAD

**Issue by lifeart** [timbru31/docker-node-chrome#382]
Reference: https://github.com/timbru31/docker-node-chrome/commit/222282d4c073cf9b50ce1dfcfd6a6cece6c88262#r108480030

Could reproduce it with `timbru31/node-chrome:16`

After changing runner from `Chrome` to `Chromium` my CI works fine, but it seems it may be broken again if changes will be rolled-back.

**Comment by manmeet90** [comment]
I am seeing same issue with 14-slim image. Breaking the ci.

**Comment by timbru31** [comment]
Uh, yes that’s unfortunate with the switch to Chromium. I’ll add a symlink to restore some compatibility.

(re-posted for visibility)

**Comment by timbru31** [comment]
I've added some symlinks in f63c61676994d80990623924e9c5394907568c24, could one of you re-test?

**Comment by lifeart** [comment]
I already switched to chromium :)
@manmeet90 could you check?

**Comment by faragos** [comment]
it works for me again as far I can test it👍

**Comment by oajulianclementson** [comment]
For some reason I had been using `/usr/bin/chromium-browser` which was presumably an alias for `google-chrome`, and no longer exists. I've switched to using `/usr/bin/chromium`.

**Comment by timbru31** [comment]
Thanks for the feedback folks! Closing for now. Let me know if you encounter further issues.
