### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by LeonEck** [timbru31/docker-node-chrome#404]
Node 20 has become the active LTS version since [v20.9.0](https://nodejs.org/en/blog/release/v20.9.0). It would be great to have an image based on node 20.

**Comment by dheid** [comment]
@LeonEck @timbru31 I added version 20. The pull request is here https://github.com/timbru31/docker-node-chrome/pull/405

**Comment by dheid** [comment]
@LeonEck @dev-wohan Could you please vote for my pull request, so that @timbru31 will look at it?

**Comment by dev-whoan** [comment]
> @LeonEck @dev-wohan Could you please vote for my pull request, so that @timbru31 will look at it?

@dheid I just saw your comment. There was a typo `wohan`, so I didn't receive any notification.
Thank you for your PR.

However @timbru31  looked at it 18 hours ago, so I hope it will be merged ASAP.
